[package]
name = "uio"
version = "0.1.1"
authors = ["Gerd Zellweger <mail@gerdzellweger.com>"]
description = "Helper library for writing linux user-space drivers with UIO."
homepage = "https://github.com/gz/rust-uio"
repository = "https://github.com/gz/rust-uio"
documentation = "http://gz.github.io/rust-uio/uio/"
readme = "README.md"
keywords = ["driver", "pci", "linux", "generic", "hardware"]
license = "MIT"

[dependencies]
fs2 = "0.4.3"
mmap = "0.1.*"
libc = "0.1.*"
